export const INVOICE_LIST_INVOICE = 'INVOICE_LIST_INVOICE'
export const INVOICE_LIST_INVOICE_FAILURE = 'INVOICE_LIST_INVOICE_FAILURE'
export const INVOICE_LIST_INVOICE_SUCCESS = 'INVOICE_LIST_INVOICE_SUCCESS'

export const INVOICE_ONE_INVOICE = 'INVOICE_ONE_INVOICE'
export const INVOICE_ONE_INVOICE_FAILURE = 'INVOICE_ONE_INVOICE_FAILURE'
export const INVOICE_ONE_INVOICE_SUCCESS = 'INVOICE_ONE_INVOICE_SUCCESS'

export const INVOICE_UPDATE_INVOICE = 'INVOICE_UPDATE_INVOICE'
export const INVOICE_UPDATE_INVOICE_FAILURE = 'INVOICE_UPDATE_INVOICE_FAILURE'
export const INVOICE_UPDATE_INVOICE_SUCCESS = 'INVOICE_UPDATE_INVOICE_SUCCESS'
