export const CUSTOMER_LIST_CUSTOMER = 'CUSTOMER_LIST_CUSTOMER'
export const CUSTOMER_LIST_CUSTOMER_FAILURE = 'CUSTOMER_LIST_CUSTOMER_FAILURE'
export const CUSTOMER_LIST_CUSTOMER_SUCCESS = 'CUSTOMER_LIST_CUSTOMER_SUCCESS'

export const CUSTOMER_ONE_CUSTOMER = 'CUSTOMER_ONE_CUSTOMER'
export const CUSTOMER_ONE_CUSTOMER_FAILURE = 'CUSTOMER_ONE_CUSTOMER_FAILURE'
export const CUSTOMER_ONE_CUSTOMER_SUCCESS = 'CUSTOMER_ONE_CUSTOMER_SUCCESS'
