export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'

export const AUTH_LOAD_DATA = 'AUTH_LOAD_DATA'
export const AUTH_LOAD_DATA_FAILURE = 'AUTH_LOAD_DATA_FAILURE'
export const AUTH_LOAD_DATA_SUCCESS = 'AUTH_LOAD_DATA_SUCCESS'
